unique(List,X):-
    unique_acc(List,[],X).
check(_,[],1).
check(V,[V|_],0):-
    !.
check(V,[_|T],Z):-
    check(V,T,Z).
unique_acc([],Acc,X):-
    reverse(Acc,X).
unique_acc([H|T],Acc,X):-
    check(H,Acc,Z),
    Z=:=1,
    !,
    unique_acc(T,[H|Acc],X).
unique_acc([_|T],Acc,X):-
    unique_acc(T,Acc,X).
